name: Terraform Deployment

on:
  push:
    branches:
      - main
      - master
      - feature/*

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.0.0"
    - name: Install AWS CLI
      run: |
        sudo apt-get update && \
        sudo apt-get install -y python3-pip && \
        sudo pip3 install awscli --upgrade
   
    - name: Configure AWS credentials
      run: |
        echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

    - name: Navigate to Terraform directory
      run: cd terraform_appache2

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform
      run: terraform plan

    - name: Apply Terraform
      run: terraform apply -auto-approve
